function MAP_info
% создание графического окна с заголовком myplotgui и без надписи Figure 1
global Modul
Modul.Minfo.H = figure(99);
clf
set(Modul.Minfo.H,'Name', 'MAP_info', 'NumberTitle', 'off')
set(Modul.Minfo.H,'Position',[100 100 420 100])

% создание осей
%hA = axes('Position', [0.1 0.2 0.8 0.7]);
% создание кнопки и задание свойству Callback значения указателя на подфункцию

Modul.Minfo.Hb = uicontrol('Style', 'pushbutton', ...
     'Position', [285 20 120 60],...
    'String', 'STOP',...
    'FontSize',18,...
    'Callback', @BtnPlotCallback);

Modul.Minfo.Htime = uicontrol('Style', 'text', ...
     'Position', [150 20 120 30],...
    'String', 0,...
    'FontSize',12);
Modul.Minfo.HtimeLabel = uicontrol('Style', 'text', ...
     'Position', [150 50 120 30],...
    'String', ['time'],...% (',int2str(Modul.Tend),')'],...
    'FontSize',12);

Modul.Minfo.Hrun = uicontrol('Style', 'text', ...
     'Position', [20 30 120 40],...
    'String', 'RUN',...
    'BackgroundColor',[0,1,0],...
    'FontSize',21);

function BtnPlotCallback(src,evt)
global Modul
Modul.Stop=true;
set(Modul.Minfo.Hrun,'String', 'STOP');
Modul
fprintf('\n-------GUI STOP------\n')